[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Alan Pancieri Berger Saar <alan.berger@ufes.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.108.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
